import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import { getLocales } from 'react-native-localize';

// Translation resources
const resources = {
  en: {
    translation: {
      // Common
      common: {
        ok: 'OK',
        cancel: 'Cancel',
        save: 'Save',
        delete: 'Delete',
        edit: 'Edit',
        add: 'Add',
        search: 'Search',
        loading: 'Loading...',
        error: 'Error',
        success: 'Success',
        retry: 'Retry',
        back: 'Back',
        next: 'Next',
        previous: 'Previous',
        done: 'Done',
        close: 'Close',
      },
      
      // Navigation
      navigation: {
        home: 'Home',
        scanner: 'Scanner',
        pricing: 'Pricing',
        profile: 'Profile',
        product: 'Product Info',
      },
      
      // Onboarding
      onboarding: {
        welcome: 'Welcome to Kuwaiti Food Scanner',
        welcomeSubtitle: 'Make healthy, informed, and economical food choices',
        personalInfo: 'Personal Information',
        healthGoals: 'Health Goals',
        dietaryPreferences: 'Dietary Preferences',
        allergies: 'Food Allergies',
        name: 'Full Name',
        email: 'Email',
        phone: 'Phone Number',
        age: 'Age',
        weight: 'Weight (kg)',
        height: 'Height (cm)',
        selectGoals: 'Select your health goals',
        selectPreferences: 'Select your dietary preferences',
        selectAllergies: 'Select your food allergies',
      },
      
      // Home
      home: {
        greeting: 'Hello, {{name}}',
        subtitle: 'What would you like to scan today?',
        quickActions: 'Quick Actions',
        recentProducts: 'Recent Products',
        healthTips: 'Health Tips',
        stats: 'Your Statistics',
        scanProduct: 'Scan Product',
        recentScans: 'Recent Scans',
        favorites: 'Favorites',
        priceAlerts: 'Price Alerts',
        viewAll: 'View All',
        scannedProducts: 'Scanned Products',
        addedPrices: 'Added Prices',
        favoritesCount: 'Favorites',
        avgHealthScore: 'Avg Health Score',
      },
      
      // Scanner
      scanner: {
        title: 'Barcode Scanner',
        instruction: 'Position the barcode within the frame to scan',
        flash: 'Flash',
        switch: 'Switch',
        helpText: 'Make sure there is adequate lighting and the barcode is clear',
        permissionTitle: 'Camera Permission',
        permissionMessage: 'This app needs camera access to scan barcodes',
        retry: 'Try Again',
        productNotFound: 'Product Not Found',
        addProductPrompt: 'The product with barcode {{barcode}} is not in our database. Would you like to add it?',
        addProduct: 'Add Product',
        comingSoon: 'Coming Soon',
      },
      
      // Product
      product: {
        nutritionalFacts: 'Nutritional Information',
        servingSize: 'Serving Size: {{size}}',
        calories: 'Calories',
        totalFat: 'Total Fat',
        saturatedFat: 'Saturated Fat',
        transFat: 'Trans Fat',
        cholesterol: 'Cholesterol',
        sodium: 'Sodium',
        totalCarbs: 'Total Carbohydrates',
        dietaryFiber: 'Dietary Fiber',
        sugars: 'Sugars',
        protein: 'Protein',
        ingredients: 'Ingredients',
        allergens: 'Allergens',
        healthScore: 'Health Score',
        healthScoreDetails: 'Health Score Details',
        halalStatus: 'Halal Status',
        halal: 'Halal',
        haram: 'Haram',
        unknown: 'Unknown',
        doubtful: 'Doubtful',
        pricing: 'Pricing',
        viewPrices: 'View Prices',
        addPrice: 'Add Price',
        outOf100: 'out of 100',
        verified: 'Verified',
        unverified: 'Unverified',
        trust: 'Trust: {{score}}%',
        report: 'Report',
        loadingProduct: 'Loading product information...',
        productNotFound: 'Product not found',
        goBack: 'Go Back',
      },
      
      // Profile
      profile: {
        personalInfo: 'Personal Information',
        healthGoals: 'Health Goals',
        dietaryPreferences: 'Dietary Preferences',
        allergies: 'Allergies',
        settings: 'Settings',
        actions: 'Actions',
        language: 'Language',
        priceAlerts: 'Price Alerts',
        newProducts: 'New Products',
        healthTips: 'Health Tips',
        shareData: 'Share Data',
        analytics: 'Analytics',
        favorites: 'Favorites',
        scanHistory: 'Scan History',
        help: 'Help & Support',
        about: 'About App',
        logout: 'Logout',
        logoutConfirm: 'Are you sure you want to logout?',
        editProfile: 'Edit Profile',
        comingSoon: 'This feature will be available soon',
        name: 'Name',
        email: 'Email',
        phone: 'Phone',
        age: 'Age',
        weight: 'Weight',
        height: 'Height',
        years: 'years',
        kg: 'kg',
        cm: 'cm',
        notSpecified: 'Not specified',
        severe: 'Severe',
        moderate: 'Moderate',
        mild: 'Mild',
      },
      
      // Pricing
      pricing: {
        title: 'Price Comparison',
        subtitle: 'Find the best prices for products',
        sortBy: 'Sort by:',
        price: 'Price',
        date: 'Date',
        store: 'Store',
        addPrice: 'Add Price',
        noPrices: 'No prices available',
        noPricesSubtitle: 'Be the first to add prices for products',
        addNewPrice: 'Add New Price',
        productName: 'Product Name',
        store: 'Store',
        priceKWD: 'Price (KWD)',
        verified: 'Verified',
        unverified: 'Unverified',
        trust: 'Trust: {{score}}%',
        report: 'Report',
        comingSoon: 'This feature will be available soon',
      },
      
      // Health Goals
      healthGoals: {
        weightLoss: 'Weight Loss',
        weightLossDesc: 'Lose weight and maintain a healthy BMI',
        muscleGain: 'Muscle Gain',
        muscleGainDesc: 'Build muscle mass and strength',
        maintenance: 'Weight Maintenance',
        maintenanceDesc: 'Maintain current weight and health',
        diabetes: 'Diabetes Management',
        diabetesDesc: 'Manage blood sugar levels',
      },
      
      // Dietary Preferences
      dietaryPreferences: {
        halal: 'Halal',
        halalDesc: 'Only Halal certified products',
        vegetarian: 'Vegetarian',
        vegetarianDesc: 'No meat or fish',
        vegan: 'Vegan',
        veganDesc: 'No animal products',
        glutenFree: 'Gluten-Free',
        glutenFreeDesc: 'No gluten containing ingredients',
        lactoseFree: 'Lactose-Free',
        lactoseFreeDesc: 'No lactose containing ingredients',
        lowSodium: 'Low Sodium',
        lowSodiumDesc: 'Reduced sodium content',
        lowSugar: 'Low Sugar',
        lowSugarDesc: 'Reduced sugar content',
      },
      
      // Allergies
      allergies: {
        nuts: 'Nuts',
        dairy: 'Dairy',
        eggs: 'Eggs',
        soy: 'Soy',
        wheat: 'Wheat',
        fish: 'Fish',
        shellfish: 'Shellfish',
        sesame: 'Sesame',
      },
      
      // Health Score
      healthScore: {
        excellent: 'Excellent',
        good: 'Good',
        fair: 'Fair',
        poor: 'Poor',
        veryPoor: 'Very Poor',
        unknown: 'Unknown',
        lowSugar: 'Low Sugar',
        lowSugarDesc: 'Contains natural sugars only',
        highProtein: 'High Protein',
        highProteinDesc: 'Good source of protein',
        naturalIngredients: 'Natural Ingredients',
        naturalIngredientsDesc: 'Made with natural ingredients',
        lowSodium: 'Low Sodium',
        lowSodiumDesc: 'Low sodium content',
        highFat: 'High Fat',
        highFatDesc: 'High fat content',
        lowFiber: 'Low Fiber',
        lowFiberDesc: 'Low fiber content',
        highVitamins: 'High Vitamins',
        highVitaminsDesc: 'High vitamin content',
      },
    },
  },
  
  ar: {
    translation: {
      // Common
      common: {
        ok: 'موافق',
        cancel: 'إلغاء',
        save: 'حفظ',
        delete: 'حذف',
        edit: 'تعديل',
        add: 'إضافة',
        search: 'بحث',
        loading: 'جاري التحميل...',
        error: 'خطأ',
        success: 'نجح',
        retry: 'إعادة المحاولة',
        back: 'رجوع',
        next: 'التالي',
        previous: 'السابق',
        done: 'تم',
        close: 'إغلاق',
      },
      
      // Navigation
      navigation: {
        home: 'الرئيسية',
        scanner: 'الماسح',
        pricing: 'الأسعار',
        profile: 'الملف الشخصي',
        product: 'معلومات المنتج',
      },
      
      // Onboarding
      onboarding: {
        welcome: 'مرحباً بك في مسح الغداء الكويتي',
        welcomeSubtitle: 'اتخذ خيارات غذائية صحية وذكية',
        personalInfo: 'المعلومات الشخصية',
        healthGoals: 'الأهداف الصحية',
        dietaryPreferences: 'التفضيلات الغذائية',
        allergies: 'الحساسيات الغذائية',
        name: 'الاسم الكامل',
        email: 'البريد الإلكتروني',
        phone: 'رقم الهاتف',
        age: 'العمر',
        weight: 'الوزن (كجم)',
        height: 'الطول (سم)',
        selectGoals: 'اختر أهدافك الصحية',
        selectPreferences: 'اختر تفضيلاتك الغذائية',
        selectAllergies: 'اختر الحساسيات التي تعاني منها',
      },
      
      // Home
      home: {
        greeting: 'مرحباً، {{name}}',
        subtitle: 'ما الذي تريد مسحه اليوم؟',
        quickActions: 'الإجراءات السريعة',
        recentProducts: 'المنتجات الأخيرة',
        healthTips: 'نصائح صحية',
        stats: 'إحصائياتك',
        scanProduct: 'مسح منتج',
        recentScans: 'المسوحات الأخيرة',
        favorites: 'المفضلة',
        priceAlerts: 'تنبيهات الأسعار',
        viewAll: 'عرض الكل',
        scannedProducts: 'منتج مسح',
        addedPrices: 'سعر أضيف',
        favoritesCount: 'مفضل',
        avgHealthScore: 'متوسط الصحة',
      },
      
      // Scanner
      scanner: {
        title: 'ماسح الباركود',
        instruction: 'ضع الباركود داخل الإطار للمسح',
        flash: 'فلاش',
        switch: 'تبديل',
        helpText: 'تأكد من وجود إضاءة كافية ووضوح الباركود',
        permissionTitle: 'إذن الكاميرا',
        permissionMessage: 'يحتاج التطبيق إلى إذن الكاميرا لمسح الباركود',
        retry: 'إعادة المحاولة',
        productNotFound: 'منتج غير موجود',
        addProductPrompt: 'المنتج بالباركود {{barcode}} غير موجود في قاعدة البيانات. هل تريد إضافته؟',
        addProduct: 'إضافة المنتج',
        comingSoon: 'ستكون هذه الميزة متاحة قريباً',
      },
      
      // Product
      product: {
        nutritionalFacts: 'المعلومات الغذائية',
        servingSize: 'حجم الحصة: {{size}}',
        calories: 'السعرات الحرارية',
        totalFat: 'الدهون الكلية',
        saturatedFat: 'الدهون المشبعة',
        transFat: 'الدهون المتحولة',
        cholesterol: 'الكوليسترول',
        sodium: 'الصوديوم',
        totalCarbs: 'الكربوهيدرات',
        dietaryFiber: 'الألياف',
        sugars: 'السكريات',
        protein: 'البروتين',
        ingredients: 'المكونات',
        allergens: 'مسببات الحساسية',
        healthScore: 'التقييم الصحي',
        healthScoreDetails: 'تفاصيل التقييم الصحي',
        halalStatus: 'الحالة الحلال',
        halal: 'حلال',
        haram: 'حرام',
        unknown: 'غير معروف',
        doubtful: 'مشكوك فيه',
        pricing: 'الأسعار',
        viewPrices: 'عرض الأسعار',
        addPrice: 'إضافة سعر',
        outOf100: 'من 100',
        verified: 'مؤكد',
        unverified: 'غير مؤكد',
        trust: 'ثقة: {{score}}%',
        report: 'إبلاغ',
        loadingProduct: 'جاري تحميل معلومات المنتج...',
        productNotFound: 'لم يتم العثور على المنتج',
        goBack: 'العودة',
      },
      
      // Profile
      profile: {
        personalInfo: 'المعلومات الشخصية',
        healthGoals: 'الأهداف الصحية',
        dietaryPreferences: 'التفضيلات الغذائية',
        allergies: 'الحساسيات',
        settings: 'الإعدادات',
        actions: 'الإجراءات',
        language: 'اللغة',
        priceAlerts: 'تنبيهات الأسعار',
        newProducts: 'منتجات جديدة',
        healthTips: 'نصائح صحية',
        shareData: 'مشاركة البيانات',
        analytics: 'التحليلات',
        favorites: 'المفضلة',
        scanHistory: 'سجل المسح',
        help: 'المساعدة والدعم',
        about: 'حول التطبيق',
        logout: 'تسجيل الخروج',
        logoutConfirm: 'هل أنت متأكد من أنك تريد تسجيل الخروج؟',
        editProfile: 'تعديل الملف الشخصي',
        comingSoon: 'ستكون هذه الميزة متاحة قريباً',
        name: 'الاسم',
        email: 'البريد الإلكتروني',
        phone: 'رقم الهاتف',
        age: 'العمر',
        weight: 'الوزن',
        height: 'الطول',
        years: 'سنة',
        kg: 'كجم',
        cm: 'سم',
        notSpecified: 'غير محدد',
        severe: 'شديدة',
        moderate: 'متوسطة',
        mild: 'خفيفة',
      },
      
      // Pricing
      pricing: {
        title: 'مقارنة الأسعار',
        subtitle: 'اعثر على أفضل الأسعار للمنتجات',
        sortBy: 'ترتيب حسب:',
        price: 'السعر',
        date: 'التاريخ',
        store: 'المتجر',
        addPrice: 'إضافة سعر',
        noPrices: 'لا توجد أسعار متاحة',
        noPricesSubtitle: 'كن أول من يضيف سعراً للمنتجات',
        addNewPrice: 'إضافة سعر جديد',
        productName: 'اسم المنتج',
        store: 'المتجر',
        priceKWD: 'السعر (د.ك)',
        verified: 'مؤكد',
        unverified: 'غير مؤكد',
        trust: 'ثقة: {{score}}%',
        report: 'إبلاغ',
        comingSoon: 'ستكون هذه الميزة متاحة قريباً',
      },
      
      // Health Goals
      healthGoals: {
        weightLoss: 'فقدان الوزن',
        weightLossDesc: 'فقدان الوزن والحفاظ على مؤشر كتلة الجسم الصحي',
        muscleGain: 'زيادة الكتلة العضلية',
        muscleGainDesc: 'بناء الكتلة العضلية والقوة',
        maintenance: 'الحفاظ على الوزن',
        maintenanceDesc: 'الحفاظ على الوزن الحالي والصحة',
        diabetes: 'إدارة السكري',
        diabetesDesc: 'إدارة مستويات السكر في الدم',
      },
      
      // Dietary Preferences
      dietaryPreferences: {
        halal: 'حلال',
        halalDesc: 'المنتجات الحلال المعتمدة فقط',
        vegetarian: 'نباتي',
        vegetarianDesc: 'بدون لحوم أو أسماك',
        vegan: 'نباتي صرف',
        veganDesc: 'بدون منتجات حيوانية',
        glutenFree: 'خالي من الغلوتين',
        glutenFreeDesc: 'بدون مكونات تحتوي على الغلوتين',
        lactoseFree: 'خالي من اللاكتوز',
        lactoseFreeDesc: 'بدون مكونات تحتوي على اللاكتوز',
        lowSodium: 'قليل الصوديوم',
        lowSodiumDesc: 'محتوى صوديوم منخفض',
        lowSugar: 'قليل السكر',
        lowSugarDesc: 'محتوى سكر منخفض',
      },
      
      // Allergies
      allergies: {
        nuts: 'المكسرات',
        dairy: 'منتجات الألبان',
        eggs: 'البيض',
        soy: 'الصويا',
        wheat: 'القمح',
        fish: 'الأسماك',
        shellfish: 'المحار',
        sesame: 'السمسم',
      },
      
      // Health Score
      healthScore: {
        excellent: 'ممتاز',
        good: 'جيد',
        fair: 'مقبول',
        poor: 'ضعيف',
        veryPoor: 'ضعيف جداً',
        unknown: 'غير معروف',
        lowSugar: 'قليل السكر',
        lowSugarDesc: 'يحتوي على سكريات طبيعية فقط',
        highProtein: 'غني بالبروتين',
        highProteinDesc: 'مصدر جيد للبروتين',
        naturalIngredients: 'مكونات طبيعية',
        naturalIngredientsDesc: 'مصنوع من مكونات طبيعية',
        lowSodium: 'قليل الصوديوم',
        lowSodiumDesc: 'محتوى صوديوم منخفض',
        highFat: 'غني بالدهون',
        highFatDesc: 'محتوى دهون عالي',
        lowFiber: 'قليل الألياف',
        lowFiberDesc: 'محتوى ألياف منخفض',
        highVitamins: 'غني بالفيتامينات',
        highVitaminsDesc: 'محتوى فيتامينات عالي',
      },
    },
  },
};

// Initialize i18n
i18n
  .use(initReactI18next)
  .init({
    resources,
    lng: 'ar', // Default to Arabic
    fallbackLng: 'en',
    interpolation: {
      escapeValue: false,
    },
    react: {
      useSuspense: false,
    },
  });

export default i18n;
